server:
    port: 1300
    servlet:
        context-path: /tasty-town

spring:
    datasource:
        url: jdbc:mysql://localhost/tasty-town
        username: root
        password: Root

    # profiles:
    #     active: prod
    
    jpa:
        hibernate:
            ddl-auto: update

        show-sql: true

upload:
    file:
        dir: images

order:
    delivery:
        fee: 49
    tax :
        rate: 0.1